use crate::{
    active_player::{self, AbilityRanks},
    data::ActivePlayer,
    dmg,
};

pub mod ahri;
pub mod orianna;

#[derive(Debug, Clone)]
pub enum Champion<'a> {
    Ahri(ahri::Ahri<'a>),
    Orianna(orianna::Orianna<'a>),
    None,
}
pub struct CalculateDamageStruct<'a> {
    pub active_player: &'a ActivePlayer,
    pub ability_ranks: &'a AbilityRanks,
    pub rotation: &'a str,
    pub resistance: &'a dmg::Resistance,
}

pub trait CalculateDamageTrait {
    fn calculate_damage(&self, items: CalculateDamageStruct) -> f64;
}

impl Champion<'_> {
    pub fn new(champion: &str) -> Self {
        match champion {
            "Ahri" => Champion::Ahri(ahri::Ahri::default()),
            "Orianna" => Champion::Orianna(orianna::Orianna::default()),
            _ => Champion::None,
        }
    }
}

impl CalculateDamageTrait for Champion<'_> {
    fn calculate_damage(&self, cds: CalculateDamageStruct) -> f64 {
        match self {
            Champion::Ahri(ahri) => ahri.calculate_damage(cds),
            Champion::Orianna(orianna) => orianna::Orianna::calculate_damage(orianna, cds),
            _ => 0.0,
        }
    }
}

// #[derive(Debug, Deserialize)]
// #[serde(rename_all = "camelCase")]
// pub struct DDragon {
//     data: Champion,
// }

// #[derive(Debug, Deserialize)]
// pub struct Stats {
//     spellblock: i32,
// }

// #[derive(Debug, Deserialize)]
// pub enum Champion {
//     Aatrox	{ stats: Stats, },
//     Ahri    { stats: Stats, },
//     Akali	{ stats: Stats, },
//     Akshan	{ stats: Stats, },
//     Alistar	{ stats: Stats, },
//     Amumu	{ stats: Stats, },
//     Anivia	{ stats: Stats, },
//     Annie	{ stats: Stats, },
//     Aphelios	{ stats: Stats, },
//     Ashe	{ stats: Stats, },
//     AurelionSol	{ stats: Stats, },
//     Azir	{ stats: Stats, },
//     Bard	{ stats: Stats, },
//     Belveth	{ stats: Stats, },
//     Blitzcrank	{ stats: Stats, },
//     Brand	{ stats: Stats, },
//     Braum	{ stats: Stats, },
//     Caitlyn	{ stats: Stats, },
//     Camille	{ stats: Stats, },
//     Cassiopeia	{ stats: Stats, },
//     Chogath	{ stats: Stats, },
//     Corki	{ stats: Stats, },
//     Darius	{ stats: Stats, },
//     Diana	{ stats: Stats, },
//     Draven	{ stats: Stats, },
//     DrMundo	{ stats: Stats, },
//     Ekko	{ stats: Stats, },
//     Elise	{ stats: Stats, },
//     Evelynn	{ stats: Stats, },
//     Ezreal	{ stats: Stats, },
//     Fiddlesticks	{ stats: Stats, },
//     Fiora	{ stats: Stats, },
//     Fizz	{ stats: Stats, },
//     Galio	{ stats: Stats, },
//     Gangplank	{ stats: Stats, },
//     Garen	{ stats: Stats, },
//     Gnar	{ stats: Stats, },
//     Gragas	{ stats: Stats, },
//     Graves	{ stats: Stats, },
//     Gwen	{ stats: Stats, },
//     Hecarim	{ stats: Stats, },
//     Heimerdinger	{ stats: Stats, },
//     Illaoi	{ stats: Stats, },
//     Irelia	{ stats: Stats, },
//     Ivern	{ stats: Stats, },
//     Janna	{ stats: Stats, },
//     JarvanIV	{ stats: Stats, },
//     Jax	{ stats: Stats, },
//     Jayce	{ stats: Stats, },
//     Jhin	{ stats: Stats, },
//     Jinx	{ stats: Stats, },
//     Kaisa	{ stats: Stats, },
//     Kalista	{ stats: Stats, },
//     Karma	{ stats: Stats, },
//     Karthus	{ stats: Stats, },
//     Kassadin	{ stats: Stats, },
//     Katarina	{ stats: Stats, },
//     Kayle	{ stats: Stats, },
//     Kayn	{ stats: Stats, },
//     Kennen	{ stats: Stats, },
//     Khazix	{ stats: Stats, },
//     Kindred	{ stats: Stats, },
//     Kled	{ stats: Stats, },
//     KogMaw	{ stats: Stats, },
//     Leblanc	{ stats: Stats, },
//     LeeSin	{ stats: Stats, },
//     Leona	{ stats: Stats, },
//     Lillia	{ stats: Stats, },
//     Lissandra	{ stats: Stats, },
//     Lucian	{ stats: Stats, },
//     Lulu	{ stats: Stats, },
//     Lux	{ stats: Stats, },
//     Malphite	{ stats: Stats, },
//     Malzahar	{ stats: Stats, },
//     Maokai	{ stats: Stats, },
//     MasterYi	{ stats: Stats, },
//     MissFortune	{ stats: Stats, },
//     MonkeyKing	{ stats: Stats, },
//     Mordekaiser	{ stats: Stats, },
//     Morgana	{ stats: Stats, },
//     Nami	{ stats: Stats, },
//     Nasus	{ stats: Stats, },
//     Nautilus	{ stats: Stats, },
//     Neeko	{ stats: Stats, },
//     Nidalee	{ stats: Stats, },
//     Nilah	{ stats: Stats, },
//     Nocturne	{ stats: Stats, },
//     Nunu	{ stats: Stats, },
//     Olaf	{ stats: Stats, },
//     Orianna	{ stats: Stats, },
//     Ornn	{ stats: Stats, },
//     Pantheon	{ stats: Stats, },
//     Poppy	{ stats: Stats, },
//     Pyke	{ stats: Stats, },
//     Qiyana	{ stats: Stats, },
//     Quinn	{ stats: Stats, },
//     Rakan	{ stats: Stats, },
//     Rammus	{ stats: Stats, },
//     RekSai	{ stats: Stats, },
//     Rell	{ stats: Stats, },
//     Renata	{ stats: Stats, },
//     Renekton	{ stats: Stats, },
//     Rengar	{ stats: Stats, },
//     Riven	{ stats: Stats, },
//     Rumble	{ stats: Stats, },
//     Ryze	{ stats: Stats, },
//     Samira	{ stats: Stats, },
//     Sejuani	{ stats: Stats, },
//     Senna	{ stats: Stats, },
//     Seraphine	{ stats: Stats, },
//     Sett	{ stats: Stats, },
//     Shaco	{ stats: Stats, },
//     Shen	{ stats: Stats, },
//     Shyvana	{ stats: Stats, },
//     Singed	{ stats: Stats, },
//     Sion	{ stats: Stats, },
//     Sivir	{ stats: Stats, },
//     Skarner	{ stats: Stats, },
//     Sona	{ stats: Stats, },
//     Soraka	{ stats: Stats, },
//     Swain	{ stats: Stats, },
//     Sylas	{ stats: Stats, },
//     Syndra	{ stats: Stats, },
//     TahmKench	{ stats: Stats, },
//     Taliyah	{ stats: Stats, },
//     Talon	{ stats: Stats, },
//     Taric	{ stats: Stats, },
//     Teemo	{ stats: Stats, },
//     Thresh	{ stats: Stats, },
//     Tristana	{ stats: Stats, },
//     Trundle	{ stats: Stats, },
//     Tryndamere	{ stats: Stats, },
//     TwistedFate	{ stats: Stats, },
//     Twitch	{ stats: Stats, },
//     Udyr	{ stats: Stats, },
//     Urgot	{ stats: Stats, },
//     Varus	{ stats: Stats, },
//     Vayne	{ stats: Stats, },
//     Veigar	{ stats: Stats, },
//     Velkoz	{ stats: Stats, },
//     Vex	{ stats: Stats, },
//     Vi	{ stats: Stats, },
//     Viego	{ stats: Stats, },
//     Viktor	{ stats: Stats, },
//     Vladimir	{ stats: Stats, },
//     Volibear	{ stats: Stats, },
//     Warwick	{ stats: Stats, },
//     Xayah	{ stats: Stats, },
//     Xerath	{ stats: Stats, },
//     XinZhao	{ stats: Stats, },
//     Yasuo	{ stats: Stats, },
//     Yone	{ stats: Stats, },
//     Yorick	{ stats: Stats, },
//     Yuumi	{ stats: Stats, },
//     Zac	{ stats: Stats, },
//     Zed	{ stats: Stats, },
//     Zeri	{ stats: Stats, },
//     Ziggs	{ stats: Stats, },
//     Zilean	{ stats: Stats, },
//     Zoe	{ stats: Stats, },
//     Zyra	{ stats: Stats, },
// }
